export const surpriseMePrompts = [
  "Une chaise en forme d'avocat",
  'Un arbre qui joue de la guitare',
  'Un guitariste marche en centre ville',
  'Des animaux se désaltères en plein soleil',
  'Un arc en ciel magnifique le long d une plage',
  "Un toucan qui porte un costume 3 pièces",
  "Un poisson en 3d qui cligne de l'oeil",
  'Un astronaute qui se pose sur une planète tropicale',
  'An oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'Une peinture de frites et d hamburgers qui dansent',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  'Une baleine qui vole au dessus d une montagne',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'Une peinture d un renard dans le même style que Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'Une peluche qui saute au dessus d un train',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'Une couverture de dessin animé avec un robot qui a des écouteurs',
  'Une peinture à l huile de la tour effeil en hiver',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'Une photo d un monstre dans une chambre rose',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'Un samourai qui marche sur la lune à côté d un cheval',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Une femme qui pose pour une photographie avec du chocolat sur les dents',
  'Un dinosaure qui vend des pop corn',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'Un barbeucue qui marche en dessin animé',
  'Une scene de disco avec des indiens et des cowboys',
  'la statue de la liberté qui boit un verre',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'Un éléphant qui vole avec une cape, photography',
  'Un homme qui tombe amoureux de son ordinateur',
  'Une photographie d un cyborg à travers Tokyo la nuit',
  'Dracula qui marche dans les rues de New York City en 1920, photographie noir et blanc',
  'Un avion blanc qui vole dans l espace avec un rat qui pilote',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
];