export const surpriseMePrompts = [
  "Une chaise en forme d'avocat",
  'Un arbre qui joue de la guitare',
  'Un guitariste marche en centre ville',
  'Des animaux se désaltères en plein soleil',
  'Un arc en ciel magnifique le long d une plage',
  "Un toucan qui porte un costume 3 pièces",
  "Un poisson en 3d qui cligne de l'oeil",
  'Un astronaute qui se pose sur une planète tropicale',
  'Une peinture à l huile d un soldat francais qui tire sur des oranges',
  'Une peinture de frites et d hamburgers qui dansent',
  'Un stylo qui pilote une voiture volante bleue',
  'King kong qui jongle avec des voitures rouges, digital art',
  'picsou qui donne un hamburger à manger à mickey, digital art',
  'Une baleine qui vole au dessus d une montagne',
  'Une peinture à lhuile d un dauphin qui saute au dessus d une voiture',
  'Une peinture d un renard dans le même style que Starry Night',
  'Une soupe chaude qui se renverse sur le sol',
  'Une peluche qui saute au dessus d un train',
  'Un couché de soleil en hiver en montagne avec du brouillard, digital art',
  '2 building futuristes qui se joignent, digital art',
  'Un rendu 3D d une mongolfiere qui passe au dessus d un lac et de montagnes',
  'Une couverture de dessin animé avec un robot qui a des écouteurs',
  'Une peinture à l huile de la tour effeil en hiver',
  'Une photo d un chat qui saute sur du feu',
  'Une photo d un monstre dans une chambre rose',
  "Une représentation en dessin animé de la joconde",
  'Un samourai qui marche sur la lune à côté d un cheval',
  'Une cadillac moderne qui roule sur les routes de paris, avec un aileron, 50mm photography',
  'Un dessin réaliste d une femme blonde avec des yeux bleus et des levres pulpeuses',
  'Un homme qui se tient devant une porte géante qui tient une épée',
  'Une femme qui pose pour une photographie avec du chocolat sur les dents',
  'Un dinosaure qui vend des pop corn',
  'Une femme qui passe l aspirateur dans une maison sale',
  'Un barbeucue qui marche en dessin animé',
  'Une scene de disco avec des indiens et des cowboys',
  'la statue de la liberté qui boit un verre',
  'Une demoiselle qui se tient à la poupe d un bateau',
  'Un herisson qui court en claquettes, Blade Runner Cyberpunk',
  'Un astronaute qui rencontre un alien sur une autre planete, photography',
  'Un éléphant qui vole avec une cape, photography',
  'Un homme qui tombe amoureux de son ordinateur',
  'Une photographie d un cyborg à travers Tokyo la nuit',
  'Dracula qui marche dans les rues de New York City en 1920, photographie noir et blanc',
  'Un avion blanc qui vole dans l espace avec un rat qui pilote',
  'Le père noel qui passe au dessus de new york, 50mm',
  'Une tortue qui vole au dessus de paris, digital art',
];